version: '2'
services:
  web:
    build: ./web/
    volumes:
      - "./web:/src"
      - /src/node_modules/
    ports:
      - "3030:3000"
    environment:
    - NODE_ENV=${NODE_ENV}
    - NODE_REGION=${NODE_REGION}
    - NODE_DEBUG=${NODE_DEBUG}
