steps:
    - name: 'ubuntu'
      args: ['cd', 'web']
    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME:$COMMIT_SHA", "."]
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME:$COMMIT_SHA"]
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
      - app
      - deploy
      - --image-url=gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME:$COMMIT_SHA
